name: Fetch RSS Feeds Daily

on:
  schedule:
    # 毎日午前6時に実行 (UTC)
    - cron: '0 21 * * *'
  workflow_dispatch:
    # 手動実行も可能

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Fetch RSS feeds
      run: node src/js/scripts/fetch-rss.js
      
    - name: Commit and push updated feeds
      run: |
        git config --global user.name 'RSS Feed Bot'
        git config --global user.email 'bot@example.com'
        git add src/data/cache/
        git commit -m "Update RSS feed cache - $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push